# WARNING: this file is not suitable for production, please use with caution
version: '3'

networks:
  private:
  public:
    external:
      name: bubble_infrastructure_bubble

services:
  web:
    image: user
    build: .
    command: gunicorn -b 0.0.0.0:5000 user.wsgi:app
    env_file:
      - ./.flaskenv
#    environment:
#      - DATABASE_URI=mongodb://localhost:27017/user
#      - CELERY_BROKER_URL=redis://localhost:6379/1
#      - CELERY_RESULT_BACKEND_URL=redis://localhost:6379/2
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=bubble"
      - "traefik.http.services.user.loadbalancer.server.port=5000"
      - "traefik.http.routers.user.rule=PathPrefix(`/api/v1/user_center`)"
#      - "traefik.http.middlewares.user.forwardauth.address=http://192.168.112.128/api/v1/user_center/auth/"
#      - "traefik.http.middlewares.user.forwardauth.authResponseHeaders=X-Auth-User-Id, X-Auth-User-Name"
#      - "traefik.http.routers.user.middlewares=user@docker"
    volumes:
      - ./user:/code/user
      - ./db/:/db/
    ports:
      - "5000:5000"
    networks:
      - private
      - public

  redis:
    image: redis
    networks:
      - private
      - public
  celery:
    image: user
    command: "celery worker -A user.celery_app:app"
    env_file:
      - ./.flaskenv
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND_URL=redis://redis:6379/2
    networks:
      - private
      - public

